routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home');

Auth::routes();

Route::get('/now', function () {
    return \Carbon\Carbon::now();
});

if (config('app.demo.enabled')) {
    Route::group(['prefix' => 'demo'], function () {
        Route::post('generate', 'DemoController@generate');
        Route::post('switch-role/{role}', 'DemoController@switchRole');
    });
}

Route::get('/otp', 'HomeController@viewOTP');
Route::get('/otp/resend', 'HomeController@resendOTP');
Route::post('/otp', 'HomeController@submitOTP');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/settings', 'HomeController@settings');
    Route::post('/settings', 'HomeController@updateSettings')->middleware('can:switchOffOTP');

    Route::group(['middleware' => ['can:navigate']], function () {
        Route::get('/home', 'HomeController@home');
        Route::get('/test', 'HomeController@test');

        Route::group(['prefix' => 'users', 'middleware' => 'can:accessUsers'], function () {
            Route::get('/', 'UserController@index')->name('users_index');
            Route::post('toggle-approve', 'UserController@toggleApprove');
        });

        Route::group(['middleware' => 'can:viewStatistics'], function () {
            Route::get('statistics', 'HomeController@statistics');
        });

        Route::group(['prefix' => 'lessons'], function () {
            Route::get('/', 'LessonController@index')->name('lessons_index');
            Route::get('{id}/approval/request', 'LessonController@requestApproval');
            Route::get('{id}/approval/cancel', 'LessonController@cancelApproval');

            Route::group(['middleware' => 'can:customizeLessons'], function () {
                Route::get('{lesson}', 'LessonController@show');
                Route::post('/', 'LessonController@update');
                Route::get('{id}/delete', 'LessonController@delete');
                Route::get('{id}/users', 'LessonController@getUserApprovals');
                Route::post('users/toggle-approve', 'LessonController@toggleApprove');
            });
        });

        Route::group(['prefix' => 'segments', 'middleware' => 'can:accessSegments'], function () {
            Route::get('/', 'SegmentController@index')->name('segments_index');
            Route::get('/sidebar', 'SegmentController@sidebarIndex');
            Route::get('create', 'SegmentController@updateView');
            Route::get('{id}/edit', 'SegmentController@updateView');
            Route::get('{id}/preview', 'SegmentController@preview');
            Route::get('{id}/delete', 'SegmentController@delete');

            Route::post('update', 'SegmentController@update');
            Route::post('{id}/edit', 'SegmentController@update');//might be deprecated
        });

        Route::group(['prefix' => 'tasks', 'middleware' => 'can:accessSegments'], function () {
            //images
            Route::post('{id}/images', 'ImageController@uploadOnTask');
            Route::post('{id}/images/{image_id}', 'ImageController@update');
            Route::post('{id}/images/{image_id}/remove', 'ImageController@remove');
        });

        Route::group(['prefix' => 'tests'], function () {
            //will proceed the statuses from /tests/id page
            // and will provide required fields for schedules and test
            //draft -> published -> started -> finished -> graded
            //Route::post('{id}/proceed', 'TestController@proceed');

            //professors
            Route::group(['namespace' => 'Professor', 'middleware' => 'can:customizeTests'], function () {
                Route::get('create', 'TestController@updateView');
                Route::get('{id}/edit', 'TestController@updateView');
                Route::get('{id}/delete', 'TestController@delete');
                Route::get('{id}/export-csv', 'TestController@exportCSV');

                Route::post('update', 'TestController@update');
                Route::post('{id}/edit', 'TestController@update');

                Route::post('{id}/start', 'TestController@start');
                Route::post('{id}/finish', 'TestController@finish');
                Route::post('{id}/auto-calculate', 'TestController@autoCalculateGrades');
                Route::post('{id}/publish-grades', 'TestController@publishGrades');

                Route::get('{id}/users/{userId}', 'TestController@userPreview');
                Route::post('{id}/users/{userId}/grade-task', 'TestController@gradeUserTask');
                Route::post('{id}/users/{userId}/auto-grade', 'TestController@autoGrade');
                Route::post('{id}/users/{userId}/publish-grade', 'TestController@publishGrade');
            });

            //students
            Route::group(['namespace' => 'Student', 'middleware' => 'can:takeTests'], function () {
                Route::post('{id}/register', 'TestController@register');
                Route::post('{id}/leave', 'TestController@leave');

                Route::post('{id}/submit', 'TestController@submit');
                Route::post('{id}/submit-final', 'TestController@submit_final');
            });

            Route::get('/', 'TestController@index')->name('tests_index');
            Route::get('{id}', 'TestController@preview');
        });
    });
});

app/Models/Lesson.php
<?php

namespace App\Models;

use App\Models\Demo\DemoableModel;
use App\Traits\Searchable;
use Auth;
use DB;

class Lesson extends DemoableModel {

    use Searchable;

    protected $search   = ['name', 'gunet_code'];
    public    $fillable = ['name', 'gunet_code', 'semester'];

    public function users() {
        return $this->belongsToMany(User::class)->withPivot('user_id', 'approved', 'created_at', 'updated_at');
    }

    public function status() {
        return $this->belongsTo(LessonUser::class, 'id', 'lesson_id')->where('user_id', Auth::user()->id);
    }


    public function pending_users() {
        return $this->belongsToMany(User::class)->wherePivot('approved', 0);
    }

    public function pending_students() {
        return $this->pending_users()->where('role', 'student');
    }

    public function pending_professors() {
        return $this->pending_users()->where('role', 'professor');
    }


    public function approved_users() {
        return $this->belongsToMany(User::class)->wherePivot('approved', 1);
    }

    public function approved_students() {
        return $this->approved_users()->where('role', 'student');
    }

    public function approved_professors() {
        return $this->approved_users()->where('role', 'professor');
    }

    public function scopePending($query) {
        return $query->whereHas('status', function ($query) {
            $query->where('approved', 0);
        });
    }

    public function scopeApproved($query) {
        return $query->whereHas('status', function ($query) {
            $query->where('approved', 1);
        });
    }

    public function scopeUnsubscribed($query) {
        return $query->has('status', '=', 0);
    }
}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Models\Lesson;
use Auth;
use Illuminate\Http\Request;
use Log;

class LessonController extends Controller {

    public function index(Request $request) {
        $lessons = Lesson::with('status');

        if (Auth::user()->role == 'admin') {
            $lessons->withCount(['pending_users', 'approved_professors', 'approved_students']);
        }

        if ($request->input('status', '') != '') {
            $lessons->{$request->status}();
        }

        if ($request->input('search', '') != '') {
            $lessons->search($request->search);
        }

        $lessons = $lessons->paginate(10);

        return view('lessons.index', ['lessons' => $lessons]);
    }

    public function show(Lesson $lesson, Request $request) {
        return $lesson;
    }

    public function update(Request $request) {
        $lesson = Lesson::updateOrCreate(['id' => $request->input('id', null)], $request->only(['name', 'gunet_code',
            'semester',
        ]));
        return redirect('lessons');
    }

    public function delete($id = null) {
        $lesson = Lesson::withCount('users')->where('id', $id)->first();
        if (is_null($id) || is_null($lesson) || $lesson->users_count > 0) {
            return back()->with(['error' => 'Lesson cannot be deleted.']);
        }
        $lesson->delete();
        return back()->with(['success' => 'Lesson deleted successfully']);
    }

    public function requestApproval($id = null) {
        $lesson = Lesson::where('id', $id)->with('status')->first();
        if (is_null($id) || is_null($lesson) || !is_null($lesson->status)) {
            return back()->with(['error' => 'Request for approval is not available for this Lesson']);
        }
        $lesson->users()->attach(['user_id' => Auth::user()->id]);
        return back()->with(['success' => 'Request for approval sent for this Lesson']);
    }

    public function cancelApproval($id = null) {
        $lesson = Lesson::where('id', $id)->with('status')->first();
        if (is_null($id) || is_null($lesson) || is_null($lesson->status) || $lesson->status->approved == 1) {
            return back()->with(['error' => 'Cancellation of approval is not available for this Lesson']);
        }
        $lesson->users()->detach(['user_id' => Auth::user()->id]);
        return back()->with(['success' => 'Request for approval sent for this Lesson']);
    }

    public function getUserApprovals($id = null) {
        $lesson = Lesson::where('id', $id)->with('users')->first();
        return $lesson;
    }

    public function toggleApprove(Request $request) {
        $lesson = Lesson::where('id', $request->lesson_id)->first();
        $user = $lesson->users()->where('users.id', $request->user_id)->first();
        $user->pivot->approved = !$user->pivot->approved;
        $user->pivot->save();
        return $user;
    }
}

resources/views/lessons/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="row-margin-bottom col-xs-12">
        <div class="row">
          <div class="col-xs-9">
            <div class="btn-group pull-left">
              <button id="status" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ucfirst(Request::input('status','all'))}} <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li @if(Request::input('status','') == '')class="active"@endif><a href="{{route('lessons_index',Request::except('page'))}}">All</a></li>
                <li @if(Request::input('status','') == 'approved')class="active"@endif><a href="{{route('lessons_index',array_merge(Request::except('page'),['status'=>'approved']))}}">Approved</a></li>
                <li @if(Request::input('status','') == 'pending')class="active"@endif><a href="{{route('lessons_index',array_merge(Request::except('page'),['status'=>'pending']))}}">Pending</a></li>
                <li @if(Request::input('status','') == 'unsubscribed')class="active"@endif><a href="{{route('lessons_index',array_merge(Request::except('page'),['status'=>'unsubscribed']))}}">Unsubscribed</a></li>
              </ul>
            </div>
            @if(Auth::user()->role == 'admin')
              <div class="btn-group margin-left-15 pull-left">
                <button class="btn btn-primary" onClick="InitUpdateLessonModal()">
                  <i class="fa fa-plus"></i> Create
                </button>
              </div>
            @endif
          </div>
          <div class="col-xs-3">
            @include('includes.assets.search-wrap', ['value'=>Request::input('search','')])
          </div>
        </div>  
      </div>  
    </div>  
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <table class="table">
            <tr>
              <th>Name</th>
              <th>Semester</th>
              <th>Code</th>
              @if(Auth::user()->role == 'admin')
                <th>Approved</th>
                <th class="text-center">Actions</th>
              @else
                <th>Status</th>
                <th class="text-center">Approval</th>
              @endif
            </tr>
            @foreach($lessons as $lesson)
              <tr>
                <td>{{$lesson->name}}</td>
                <td>{{$lesson->semester}}</td>
                <td>{{$lesson->gunet_code}}</td>
                <td>
                @if(Auth::user()->role == 'admin')
                  @if($lesson->approved_professors_count > 0)
                    <span class="label label-professor">{{$lesson->approved_professors_count}}</span>
                  @endif
                  @if($lesson->approved_students_count > 0)
                    <span class="label label-student">{{$lesson->approved_students_count}}</span>
                  @endif
                @else
                  @if(is_null($lesson->status))
                    Unsubscribed
                  @elseif($lesson->status->approved == 0)
                    Pending
                  @elseif($lesson->status->approved == 1)
                    Approved
                  @endif
                @endif
                </td>
                <td class="text-center">
                  @if(Auth::user()->role == 'admin')
                    <button class="btn btn-{{$lesson->pending_users_count == 0 ? 'default': 'primary'}} btn-xs" onClick="InitLessonUserApprovalModal({{$lesson->id}})">
                      <i class="fa fa-users"></i>
                    </button>
                    <button class="btn btn-default btn-xs" onClick="InitUpdateLessonModal({{$lesson->id}})">
                      <i class="fa fa-pencil"></i>
                    </button>
                    <a href="{{url('lessons/'.$lesson->id.'/delete')}}" type="button" class="btn btn-danger btn-xs">
                      <i class="fa fa-trash"></i>
                    </a>
                  @else
                    @if(is_null($lesson->status))
                      <a href="{{url('lessons/'.$lesson->id.'/approval/request')}}" type="button" class="btn btn-success btn-xs">
                        Request
                      </a>
                    @else
                      <a href="{{url('lessons/'.$lesson->id.'/approval/cancel')}}" type="button" class="btn btn-danger btn-xs @if($lesson->status->approved == 1) disabled @endif" @if($lesson->status->approved == 1) disabled @endif>
                        Revoke
                      </a>
                    @endif
                  @endif
                </td>
              </tr>
            @endforeach
          </table>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <nav class="pull-right" aria-label="Page navigation">
          {{ $lessons->appends(Request::except('page'))->links() }}
        </nav>
      </div>
    </div>
  </div>
  
  
  <div class="modal fade lesson-update-modal" role="dialog">
    <div class="modal-dialog" role="document">
      <form method="POST" action="{{URL::to('lessons')}}">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><span class="action-create">Create</span><span class="action-update hidden">Update</span> Lesson</h4>
          </div>
          <div class="modal-body">
            <input type="hidden" name="id">
            <input type="hidden" name="_token" value="{{csrf_token()}}">
            <div class="row-margin-bottom">
              <label>Name:</label>
              <input type="text" class="form-control" name="name" placeholder="Course Name" required>
            </div>
            <div class="row-margin-bottom">
              <label>Code:</label>
              <input type="text" class="form-control" name="gunet_code" placeholder="Code" required>
            </div>
            <div class="row-margin-bottom">
              <label>Semester:</label>
              <input type="number" class="form-control" name="semester" placeholder="Semester">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal" aria-label="Close">Cancel</button>
            <button type="submit" class="btn btn-primary"><span class="action-create">Create</span><span class="action-update hidden">Update</span></button>
          </div>
        </div>
      </form>
    </div>
  </div>
  
  <div class="modal fade lesson-users-modal" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Course Approval Requests</h4>
        </div>
        <div class="modal-body">
          <table class="table table-bordered">
            <tr><th>Name</th><th>Email</th><th>Role</th><th>Approved</th></tr>
          </table>
        </div>
      </div>
    </div>
  </div>
  
@endsection

@section('scripts')
  <script type="text/javascript">
    var approvalsChanged = false

    let modals = {
      lessonUsers: $('.lesson-users-modal'),
      lessonUpdate: $('.lesson-update-modal'),
    }

    function InitUpdateLessonModal(id=null){
      const editableFields = ['id','name','gunet_code','semester'];
      if(id == null){
        modals.lessonUpdate.find('span.action-update').addClass('hidden')
        modals.lessonUpdate.find('span.action-create').removeClass('hidden')
        $.each( editableFields, function(key,val) {
          modals.lessonUpdate.find('input[name="'+val+'"]').val('')
        });
        modals.lessonUpdate.modal('show')
      } else {
        modals.lessonUpdate.find('span.action-create').addClass('hidden')
        modals.lessonUpdate.find('span.action-update').removeClass('hidden')
        $.ajax({
          type: "GET",
          url: baseURL+'/lessons/'+id,
          success: function(data){
            $.each( editableFields, function(key,val) {
              modals.lessonUpdate.find('input[name="'+val+'"]').val(data[val])
            });
            modals.lessonUpdate.modal('show')
          }
        })
      }
    }
    
    function InitLessonUserApprovalModal(id){
      $.ajax({
        type: "GET",
        url: baseURL+'/lessons/'+id+'/users',
        success: function(data){
          var table = modals.lessonUsers.find('.modal-body table');
          table.find('.custom-row').remove();
          $.each( data.users, function(key,value) {
            var row = '<tr class="custom-row">'
             row +=   '<td>'+value.name+'</td>'
             row +=   '<td>'+value.email+'</td>'
             row +=   '<td><span class="label label-'+value.role+'">'+value.role+'</span></td>'
             row +=   '<td>'
             row +=     '<label class="toggle" data-user-id="'+value.id+'" data-lesson-id="'+id+'">'
             row +=       '<input type="checkbox" '+ (value.pivot.approved == 1 ? 'checked' : '')+'>'
             row +=       '<span class="slider"></span></label></td>'
             row += '</tr>'
            table.append(row)
          });
          modals.lessonUsers.modal('show')
        }
      })
    }
      
    $(document).on('change','.lesson-users-modal .custom-row .toggle input',function(){
      let input = $(this)
      const value = input.prop('checked')
      let toggle = input.closest('.toggle')
      $.post( baseURL+'/lessons/users/toggle-approve',
        { 
          _token: CSRF,
          lesson_id : toggle.attr('data-lesson-id'),
          user_id : toggle.attr('data-user-id'),
        }
      )
      .fail(function( data ) {
        setTimeout(function(){
          input.prop('checked',!value)
        },200)
      })
      .done(function(data){
        approvalsChanged = true;
      });
    })

    modals.lessonUsers.on('hidden.bs.modal', function (e) {
      if(approvalsChanged)
        location.reload()
    })
  </script>
@endsection